apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: serviceb
spec:
  selector:
    matchLabels:
      app: serviceB
      service: serviceb
  action: ALLOW
  rules:
  - from:
    - source:
        principals: 
        - cluster.local/ns/projectA/sa/serviceA
        - cluster.local/ns/projectA/sa/serviceA
        - cluster.local/ns/projectA/sa/serviceA
        - cluster.local/ns/projectA/sa/service3
        - cluster.local/ns/projectA/sa/service3
        - cluster.local/ns/projectA/sa/service3
        